In [3]:
import pandas as pd

In [ ]:
df = pd.read_csv(r"C:\Masterpiece By Nickopusan\Document\Two Centuries Races\TWO_CENTURIES_OF_UM_RACES.csv", low_memory=False)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7461195 entries, 0 to 7461194
Data columns (total 13 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Year of event              int64
 1   Event dates                object
 2   Event name                 object
 3   Event distance/length      object
 4   Event number of finishers  int64
 5   Athlete performance        object
 6   Athlete club               object
 7   Athlete country            object
 8   Athlete year of birth      float64
 9   Athlete gender             object
 10  Athlete age category       object
 11  Athlete average speed      object
 12  Athlete ID                 int64
dtypes: float64(1), int64(3), object(9)
memory usage: 740.0+ MB

In [ ]:
df['Athlete year of birth'] = df['Athlete year of birth'].astype('Int64')

In [ ]:
df['Athlete average speed'] = pd.to_numeric(df['Athlete average speed'], errors='coerce')
df['Event dates'] = pd.to_datetime(df['Event dates'], errors='coerce')
df['Event dates'] = df['Event dates'].dt.strftime('%Y-%m-%d')
df = df.astype({
    "Athlete average speed": "float64",
})

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7461195 entries, 0 to 7461194
Data columns (total 13 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Year of event              int64
 1   Event dates                object
 2   Event name                 object
 3   Event distance/length      object
 4   Event number of finishers  int64
 5   Athlete performance        object
 6   Athlete club               object
 7   Athlete country            object
 8   Athlete year of birth      Int64
 9   Athlete gender             object
 10  Athlete age category       object
 11  Athlete average speed      float64
 12  Athlete ID                 int64
dtypes: Int64(1), float64(1), int64(3), object(8)
memory usage: 747.1+ MB

In [ ]:
df.duplicated().sum()

np.int64(53)

In [ ]:
df.drop_duplicates()

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,2018-06-01,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978,M,M35,10.286,0
1,2018,2018-06-01,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981,M,M35,9.501,1
2,2018,2018-06-01,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987,M,M23,9.472,2
3,2018,2018-06-01,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976,M,M40,8.976,3
4,2018,2018-06-01,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992,M,M23,8.469,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7461190,1995,NaN,La SainteLyon 65 km (FRA),65km,2,4:33:20 h,NaN,FRA,<NA>,M,NaN,14268.000,1151060
7461191,1995,NaN,La SainteLyon 65 km (FRA),65km,2,6:05:15 h,NaN,FRA,<NA>,F,NaN,10678.000,1073520
7461192,1995,NaN,Szombathely 24 hours running Race (HUN),24h,3,241.000 km,*Budapest,HUN,1950,M,M40,10042.000,1047373
7461193,1995,NaN,Szombathely 24 hours running Race (HUN),24h,3,228.000 km,*Szeged,HUN,1959,M,M35,9500.000,380150
7461194,1995,NaN,Szombathely 24 hours running Race (HUN),24h,3,224.000 km,*Pecs,HUN,1958,M,M35,9333.000,1070482

In [ ]:
df.isnull().sum()

Year of event                      0
Event dates                  5405753
Event name                         0
Event distance/length           1053
Event number of finishers          0
Athlete performance                2
Athlete club                 2826524
Athlete country                    3
Athlete year of birth         588161
Athlete gender                     7
Athlete age category          584938
Athlete average speed           7900
Athlete ID                         0
dtype: int64

In [ ]:
df[df['Athlete average speed'].isnull()]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
9494,2018,NaN,Le Dernier Homme Debout - Andenne (BEL),24h,73,131.400 km,NaN,BEL,1970,M,M45,NaN,8832
9495,2018,NaN,Le Dernier Homme Debout - Andenne (BEL),24h,73,124.100 km,NaN,BEL,1991,M,M23,NaN,8833
9496,2018,NaN,Le Dernier Homme Debout - Andenne (BEL),24h,73,116.800 km,NaN,FRA,1990,M,M23,NaN,8834
9497,2018,NaN,Le Dernier Homme Debout - Andenne (BEL),24h,73,109.500 km,NaN,BEL,1979,M,M35,NaN,8835
9498,2018,NaN,Le Dernier Homme Debout - Andenne (BEL),24h,73,102.200 km,NaN,BEL,1988,M,M23,NaN,8836
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6805771,2015,NaN,Løpevennenes Ultraintervall (NOR),16h,5,69.300 km,NaN,NOR,1977,M,M35,NaN,471458
6805772,2015,NaN,Løpevennenes Ultraintervall (NOR),16h,5,63.000 km,NaN,NOR,1988,F,W23,NaN,755015
6805773,2015,NaN,Løpevennenes Ultraintervall (NOR),16h,5,63.000 km,NaN,NOR,1973,M,M40,NaN,290991
6805774,2015,NaN,Løpevennenes Ultraintervall (NOR),16h,5,56.700 km,NaN,NOR,<NA>,M,NaN,NaN,1518202
6824338,1809,NaN,1000 miles Newmarket (GBR),1000mi,1,0:00:00 h,Performance: 999:37:00...,GBR,<NA>,M,M23,NaN,1520515

In [ ]:
df = df.dropna(subset=['Athlete average speed', 'Athlete year of birth', 'Athlete age category'], how="all")

In [ ]:
df.shape

(7460752, 13)

In [ ]:
df.isnull().sum()

Year of event                      0
Event dates                  5405417
Event name                         0
Event distance/length           1053
Event number of finishers          0
Athlete performance                0
Athlete club                 2826149
Athlete country                    1
Athlete year of birth         587718
Athlete gender                     5
Athlete age category          584495
Athlete average speed           7457
Athlete ID                         0
dtype: int64

In [ ]:
df = df.dropna(subset=['Event dates', 'Athlete club', 'Athlete year of birth', 'Athlete age category'], how='all')

In [ ]:
df.isnull().sum()

Year of event                      0
Event dates                  5127074
Event name                         0
Event distance/length           1053
Event number of finishers          0
Athlete performance                0
Athlete club                 2547806
Athlete country                    1
Athlete year of birth         309375
Athlete gender                     4
Athlete age category          306152
Athlete average speed           7457
Athlete ID                         0
dtype: int64

In [ ]:
df.shape

(7182409, 13)

In [ ]:
df.head()

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,2018-06-01,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978,M,M35,10.286,0
1,2018,2018-06-01,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981,M,M35,9.501,1
2,2018,2018-06-01,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987,M,M23,9.472,2
3,2018,2018-06-01,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976,M,M40,8.976,3
4,2018,2018-06-01,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992,M,M23,8.469,4

In [ ]:
df.drop("Event dates", axis=1, inplace=True)

In [ ]:
df.head()

,Year of event,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978,M,M35,10.286,0
1,2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981,M,M35,9.501,1
2,2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987,M,M23,9.472,2
3,2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976,M,M40,8.976,3
4,2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992,M,M23,8.469,4

In [ ]:
df.to_csv("Two Centuries Races.csv", index=False)