In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Masterpiece By Nickopusan\Document\Two Centuries Races\Two Centuries Races.csv")
df.head()

,Year of event,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4

In [3]:
df.shape

(7182409, 12)

In [4]:
df.loc[~df['Athlete club'].str.contains('[a-zA-Z]', na=False), 'Athlete club'] = ''
df.head()

,Year of event,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4

In [5]:
df

,Year of event,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4
...,...,...,...,...,...,...,...,...,...,...,...,...
7182404,1995,Les 24 heures de Fleurbaix (FRA),24h,2,232.810 km,,FRA,1958.0,M,M35,9700.000,1069476
7182405,1995,Les 24 heures de Fleurbaix (FRA),24h,2,221.374 km,,BEL,1951.0,M,M40,9224.000,1045647
7182406,1995,Szombathely 24 hours running Race (HUN),24h,3,241.000 km,*Budapest,HUN,1950.0,M,M40,10042.000,1047373
7182407,1995,Szombathely 24 hours running Race (HUN),24h,3,228.000 km,*Szeged,HUN,1959.0,M,M35,9500.000,380150
7182408,1995,Szombathely 24 hours running Race (HUN),24h,3,224.000 km,*Pecs,HUN,1958.0,M,M35,9333.000,1070482

In [6]:
df.isnull().sum()

Year of event                     0
Event name                        0
Event distance/length          1053
Event number of finishers         0
Athlete performance               0
Athlete club                      0
Athlete country                   1
Athlete year of birth        309375
Athlete gender                    4
Athlete age category         306152
Athlete average speed          7457
Athlete ID                        0
dtype: int64

In [7]:
df[df['Athlete year of birth'].notnull() & df['Athlete age category'].isnull()]

,Year of event,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
70455,2018,Zhenxibao (Cinsbu) 54 km Ultramarathon (TPE),54km,926,8:48:43 h,,TPE,1988.0,X,NaN,6.128,63250
145219,2018,Cape Cod 50K Trail Race (USA),50km,50,6:26:26 h,"*Plymouth, MA",USA,1999.0,X,NaN,7.763,120517
282231,2018,Silver State 50 Mile (USA),50mi,79,12:22:41 h,"*San Francisco, CA",USA,1975.0,X,NaN,6.501,201998
537612,2018,Javelina Jangover Night Run 50K (USA),50km,48,6:56:34 h,"*Mesa, AZ",USA,2017.0,M,NaN,7.202,331151
541388,2018,Wienerwald Ultra Trail (AUT),55km,123,7:21:09 h,,AUT,1961.0,M,NaN,7.480,59183
...,...,...,...,...,...,...,...,...,...,...,...,...
6948280,1990,Les 100 km de Millau (FRA),100km,959,13:12:00 h,,FRA,1991.0,M,NaN,7576.000,38582
7066751,1993,100 km de Amiens (FRA),100km,291,10:21:06 h,*Senlis,FRA,1961.0,NaN,NaN,9660.000,1631951
7066811,1993,100 km de Amiens (FRA),100km,291,11:36:41 h,*Villers Bretonneux,FRA,1957.0,NaN,NaN,8612.000,1631962
7101134,1993,Crown King Scramble 50K (USA),50km,101,7:55:01 h,,USA,1996.0,M,NaN,6316.000,366866
7104251,1994,Brindabella Classic (AUS),53.8km,91,6:00:05 h,,AUS,1994.0,M,NaN,8965.000,1635405

In [8]:
df.dropna(subset=['Athlete year of birth', 'Athlete age category'])

,Year of event,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4
...,...,...,...,...,...,...,...,...,...,...,...,...
7182404,1995,Les 24 heures de Fleurbaix (FRA),24h,2,232.810 km,,FRA,1958.0,M,M35,9700.000,1069476
7182405,1995,Les 24 heures de Fleurbaix (FRA),24h,2,221.374 km,,BEL,1951.0,M,M40,9224.000,1045647
7182406,1995,Szombathely 24 hours running Race (HUN),24h,3,241.000 km,*Budapest,HUN,1950.0,M,M40,10042.000,1047373
7182407,1995,Szombathely 24 hours running Race (HUN),24h,3,228.000 km,*Szeged,HUN,1959.0,M,M35,9500.000,380150
7182408,1995,Szombathely 24 hours running Race (HUN),24h,3,224.000 km,*Pecs,HUN,1958.0,M,M35,9333.000,1070482

In [9]:
# Calculate the age of the athlete
df['Calculated Age'] = df['Year of event'] - df['Athlete year of birth']

In [10]:
# Fill NaN values in 'Calculated Age' with a placeholder value before converting to integers
df['Calculated Age'].fillna(-1, inplace=True)
df['Athlete age category'].fillna(df['Calculated Age'].astype(int).astype(str), inplace=True)

C:\Users\mochw\AppData\Local\Temp\ipykernel_5616\3557817369.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Calculated Age'].fillna(-1, inplace=True)
C:\Users\mochw\AppData\Local\Temp\ipykernel_5616\3557817369.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Athlete age category'].fillna(df['Calculated Age'].astype(int).astype(str), inplace=True)

In [11]:
# Define age bins and labels
bins = [0, 20, 30, 40, 50, 60, 70, 80, 90, 100]
labels = ['0-20', '20-30', '30-40', '40-50', '50-60', '60-70', '70-80', '80-90', '90-100']

# Create a new column 'Age Group' based on the bins
df['Age Group'] = pd.cut(df['Calculated Age'], bins=bins, labels=labels, right=False)

df.head()

,Year of event,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID,Calculated Age,Age Group
0,2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0,40.0,40-50
1,2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1,37.0,30-40
2,2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2,31.0,30-40
3,2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3,42.0,40-50
4,2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4,26.0,20-30

In [12]:
df.drop('Athlete age category', axis=1, inplace=True)

In [13]:
df['Athlete club'].replace('', 'Others', inplace=True)
df.head()

C:\Users\mochw\AppData\Local\Temp\ipykernel_5616\2143055756.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Athlete club'].replace('', 'Others', inplace=True)

,Year of event,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete average speed,Athlete ID,Calculated Age,Age Group
0,2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,10.286,0,40.0,40-50
1,2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,9.501,1,37.0,30-40
2,2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,9.472,2,31.0,30-40
3,2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,8.976,3,42.0,40-50
4,2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,8.469,4,26.0,20-30

In [14]:
df.isnull().sum()

Year of event                     0
Event name                        0
Event distance/length          1053
Event number of finishers         0
Athlete performance               0
Athlete club                      0
Athlete country                   1
Athlete year of birth        309375
Athlete gender                    4
Athlete average speed          7457
Athlete ID                        0
Calculated Age                    0
Age Group                    309424
dtype: int64

In [15]:
# Add 'Unknown' to the categories of 'Age Group'
df['Age Group'] = df['Age Group'].cat.add_categories('Unknown')
df['Age Group'].fillna('Unknown', inplace=True)
df.head()

C:\Users\mochw\AppData\Local\Temp\ipykernel_5616\1323971027.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age Group'].fillna('Unknown', inplace=True)

,Year of event,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete average speed,Athlete ID,Calculated Age,Age Group
0,2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,10.286,0,40.0,40-50
1,2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,9.501,1,37.0,30-40
2,2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,9.472,2,31.0,30-40
3,2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,8.976,3,42.0,40-50
4,2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,8.469,4,26.0,20-30

In [16]:
df.fillna('Unknown', inplace=True)
df.head()

C:\Users\mochw\AppData\Local\Temp\ipykernel_5616\1108203808.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna('Unknown', inplace=True)

,Year of event,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete average speed,Athlete ID,Calculated Age,Age Group
0,2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,10.286,0,40.0,40-50
1,2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,9.501,1,37.0,30-40
2,2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,9.472,2,31.0,30-40
3,2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,8.976,3,42.0,40-50
4,2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,8.469,4,26.0,20-30

In [17]:
df.to_csv("Two Centuries Races Clean.csv", index=False)

In [18]:
df.isnull().sum()

Year of event                0
Event name                   0
Event distance/length        0
Event number of finishers    0
Athlete performance          0
Athlete club                 0
Athlete country              0
Athlete year of birth        0
Athlete gender               0
Athlete average speed        0
Athlete ID                   0
Calculated Age               0
Age Group                    0
dtype: int64

In [19]:
df[df['Athlete average speed'].notnull()]

,Year of event,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete average speed,Athlete ID,Calculated Age,Age Group
0,2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,10.286,0,40.0,40-50
1,2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,9.501,1,37.0,30-40
2,2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,9.472,2,31.0,30-40
3,2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,8.976,3,42.0,40-50
4,2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,8.469,4,26.0,20-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7182404,1995,Les 24 heures de Fleurbaix (FRA),24h,2,232.810 km,Others,FRA,1958.0,M,9700.0,1069476,37.0,30-40
7182405,1995,Les 24 heures de Fleurbaix (FRA),24h,2,221.374 km,Others,BEL,1951.0,M,9224.0,1045647,44.0,40-50
7182406,1995,Szombathely 24 hours running Race (HUN),24h,3,241.000 km,*Budapest,HUN,1950.0,M,10042.0,1047373,45.0,40-50
7182407,1995,Szombathely 24 hours running Race (HUN),24h,3,228.000 km,*Szeged,HUN,1959.0,M,9500.0,380150,36.0,30-40
7182408,1995,Szombathely 24 hours running Race (HUN),24h,3,224.000 km,*Pecs,HUN,1958.0,M,9333.0,1070482,37.0,30-40